version: '3'
services:

    #PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: digitalocean.com/php
        container_name: app
        restart: unless-stopped
        tty: true
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./DockerConf/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
        networks:
            - app-network

    #Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: unless-stopped
        tty: true
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./DockerConf/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql
        container_name: db
        restart: always
        volumes:
            - ./MySQLBase:/var/lib/mysql
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: osagoDB
            MYSQL_ROOT_PASSWORD: Qq123456
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network

    #Adminer
    adminer:
        image: adminer
        container_name: adminer
        restart: always
        ports:
            - 999:8080
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
#Volumes
volumes:
    dbdata:
        driver: local
