version: '3'

services:

    #PHP Service
    php-fpm:
        build:
            context: docker/php-fpm
        volumes:
            - ./:/var/www
        container_name: php-fpm
        restart: unless-stopped
        tty: true
        environment:
            XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
            PHP_IDE_CONFIG: "serverName=Docker"
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        networks:
            - app-network

    #Nginx Service
    webserver:
        build:
            context: docker/nginx
        volumes:
            - ./:/var/www
        ports:
            - "80:80"
        container_name: webserver
        restart: unless-stopped
        tty: true
        networks:
            - app-network

    #MySQL Service
    db:
        image: mysql
        container_name: db
        restart: always
        volumes:
            - ./MySQLBase:/var/lib/mysql
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: osagoDB
            MYSQL_ROOT_PASSWORD: Qq123456
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - app-network

    #Adminer
    adminer:
        image: adminer
        restart: always
        ports:
            - "9090:8080"
        networks:
            - app-network

#Docker Networks
networks:
    app-network:
        driver: bridge
